#!/bin/bash
# A wrapper around btrfs send
# Performs an incremental send if both from-snapshot and to-snapshot are presend
# otherwise perform a full send of to-snapshot

SNAPSHOT=$1
PREV=$2

if [ ! -e "$PREV" ]; then
	btrfs send $SNAPSHOT | cat
else
	btrfs send -p $PREV $SNAPSHOT | cat
fi