#!/bin/bash
# script for getting certbot to issue ssl certificates

cat /etc/haproxy/https-domains | while read FQDN; do
  if [ "$FQDN" != "" ]; then
  	certbot certonly --webroot --quiet --keep --agree-tos --webroot-path /etc/haproxy/certbot --email $1 -d $FQDN
  fi
done
