#!/usr/bin/python3

import fcntl, time

f = open("/tmp/infr-host-lock", "w")
try:
    fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB)
except BlockingIOError:
    print("ALREADY LOCKED")
    exit(1)

print("LOCKED")

while True:
    time.sleep(365*24*3600)
