package main

import (
	"fmt"
)

func configCmd(args []string) {
	if len(args) == 0 {
		configViewCmd(args)
	} else {
		switch args[0] {
		case "view":
			configViewCmd(parseFlags(args, noFlags))
		case "set":
			configSetCmd(parseFlags(args, noFlags))
		case "unset":
			configUnsetCmd(parseFlags(args, noFlags))
		default:
			errorExit("Invalid command: %s", args[0])
		}
	}
}

const configHelp = `Usage: infr config view [<name>]
       infr config set <name> <value>
       infr config unset <name>

View, set, or unset configuration strings used by other commands.

CONFIGURATION ITEMS:
====================

DNS:

FQDNs of hosts/containers are generated by concatenating the host container
name to the settings <dnsPrefix> and <dnsDomain>:
	FQDN = <host/container name>.<dnsPrefix>.<dnsDomain>

dnsDomain   Top level domain (aka zone) for automatically generated FQDNs

dnsPrefix   Prefix to dnsDomain for automatically generated FQDNs

If <dnsRage4..> settings are set, the Rage4 (https://rage4.com) API will be
used to automatically publish DNS records. The Rage4 API will only publish
subdomains of <dnsPrefix>.<dnsDomain>, other subdomains of <dnsDomain> will
not be touched.

dnsRage4Account  	Rage 4 account used for publishing DNS records

dnsRage4Key		Rage 4 account key used for publishing DNS records

`

func configViewCmd(args []string) {
	switch len(args) {
	case 0:

		for key, value := range config.General {
			fmt.Printf("%s: %s\n", key, value)
		}

	case 1:
		name := args[0]
		value, ok := config.General[name]

		if ok {
			fmt.Println(value)
		} else {
			errorExit("No config for: %s", name)
		}
	default:
		errorExit("Too many arguments for 'view'.")
	}
}

func configSetCmd(args []string) {
	if len(args) == 0 || len(args) > 2 {
		errorExit("Wrong number of arguments for 'set'.")
	}

	config.General[args[0]] = args[1]
	saveConfig()
}

func configUnsetCmd(args []string) {
	if len(args) != 1 {
		errorExit("Wrong number of arguments for 'unset'.")
	}

	delete(config.General, args[0])
	saveConfig()
}

func generalConfig(name string) string {
	return config.General[name]
}

func needGeneralConfig(name string) string {
	value, ok := config.General[name]
	if !ok {
		errorExit("'%s' not configured. Use `infr config set %s <value>` to configure.", name, name)
	}

	return value
}
