package main

import (
	"bytes"
	"os"
	"os/exec"
)

func helpCmd(args []string) {
	var topic string

	switch len(args) {
	case 0:
		topic = "summary"
	case 1:
		topic = args[0]
	default:
		errorExit("Too many arguments for 'help'")
	}

	topicFile, ok := filesMap["help/"+topic]

	if !ok {
		errorExit("No help for topic: %s", topic)
	}

	cmd := exec.Command("man", "-l", "-")
	cmd.Stdin = bytes.NewBufferString(topicFile)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	err := cmd.Run()
	if err != nil {
		errorExit("Error formatting help: %s", err)
	}
}

const help = `.TH INFR 1
.SH NAME
infr \- manage virtual hosting infrastructure
.SH USAGE
.P
\fBinfr\fR [\fIoptions\fR] \fBhosts\fR [\fBlist\fR]
.br
\fBinfr\fR [\fIoptions\fR] \fBhosts\fR \fBadd\fR [\fB-p\fR \fIroot-password\fR] \fIname\fR \fItarget IP address\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBhost\fR \fIname\fR \fBreconfigure\fR [\fB-n\fR] [\fB-s\fR] [\fB-k\fR] [\fB-R\fR]
.br
\fBinfr\fR [\fIoptions\fR] \fBhost\fR \fIname\fR \fBremove\fR
.P
\fBinfr\fR [\fIoptions\fR] \fBlxcs\fR [\fBlist\fR]
.br
\fBinfr\fR [\fIoptions\fR] \fBlxcs\fR \fBadd\fR \fIname\fR \fIdistribution\fR \fIrelease\fR \fIhost\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBlxc\fR \fIname\fR [\fBshow\fR]
.br
\fBinfr\fR [\fIoptions\fR] \fBlxc\fR \fIname\fR \fBadd-alias\fR \fIFQDN\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBlxc\fR \fIname\fR \fBremove-alias\fR \fIFQDN\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBlxc\fR \fIname\fR \fBhttp\fR \fBNONE\fR|\fBFORWARD\fR|\fBREDIRECT\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBlxc\fR \fIname\fR \fBhttps\fR \fBNONE\fR|\fBFORWARD\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBlxc\fR \fIname\fR \fBremove\fR
.P
\fBinfr\fR [\fIoptions\fR] \fBbackups\fR [\fBlist\fR]
.br
\fBinfr\fR [\fIoptions\fR] \fBbackups\fR \fBstart\fR \fIfrom-host\fR \fIto-host\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBbackups\fR \fBstop\fR \fIfrom-host\fR \fIto-host\fR
.P
\fBinfr\fR [\fIoptions\fR] \fBconfig\fR [\fBshow\fR [\fIname\fR]]
.br
\fBinfr\fR [\fIoptions\fR] \fBconfig\fR \fBset\fR \fIname\fR \fIvalue\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBconfig\fR \fBunset\fR \fIname\fR \fIvalue\fR
.P
\fBinfr\fR [\fIoptions\fR] \fBkeys\fR [\fBlist\fR]
.br
\fBinfr\fR [\fIoptions\fR] \fBkeys\fR \fBadd\fR \fIkeyfile\fR
.br
\fBinfr\fR [\fIoptions\fR] \fBkeys\fR \fBremove\fR \fIkeyfile\fR
.P
\fBinfr\fR [\fIoptions\fR] \fBdns\fR [\fBlist\fR]
.br
\fBinfr\fR [\fIoptions\fR] \fBdns\fR \fBfix\fR
.P
\fBinfr\fR [\fIoptions\fR] \fBhelp\fR
.SH DESCRIPTION
\fBinfr\fR is a tool for managing a virtual infrastructure of lxc containers running in a distributed set of virtual machines ...
.SH GLOBAL OPTIONS
.TP
\fB\-\-workdir\fR=\fIworkdir\fR
.br
Set working directory where config files and other state are stored. Defaults to ~/.infr.
.SH CONFIGURATION
.P
DNS:
.P
FQDNs of hosts/containers are generated by concatenating the host container
name to the settings <dnsPrefix> and <dnsDomain>:
	FQDN = <host/container name>.<dnsPrefix>.<dnsDomain>
.P
dnsDomain   Top level domain (aka zone) for automatically generated FQDNs
.P
dnsPrefix   Prefix to dnsDomain for automatically generated FQDNs
.P
If <dnsRage4..> settings are set, the Rage4 (https://rage4.com) API will be
used to automatically publish DNS records. The Rage4 API will only publish
subdomains of <dnsPrefix>.<dnsDomain>, other subdomains of <dnsDomain> will
not be touched.
.P
dnsRage4Account  	Rage 4 account used for publishing DNS records
.P
dnsRage4Key		Rage 4 account key used for publishing DNS records
.SH HOST COMMANDS
.P
\fBinfr\fR [\fIoptions\fR] \fBhosts\fR \fBadd\fR [\fB-p\fR \fIroot-password\fR] \fIname\fR \fItarget IP address\fR
.P
Add new host to cluster by sshing into root@<target IP address>, reformating the harddrive,
installing and configuring new operating system and other software.
.P
THIS WILL DESTROY ALL DATA ON THE MACHINE AT <target IP address>. It is designed to be used with a
brand new VPS containing no data, USE ON AN EXISTING MACHINE AT YOUR OWN RISK.
.P
This command uses the ssh key in $HOMEDIR/.ssh/id_rsa or the password provided by the -p flag to
authenticate with the target host.
.P
Before using this command you need to use:
infr keys add <keyfile> -- to specify ssh keys to be installed on new host.
infr config set infrDomain <domain> -- to specify domain that will be appended to <name> to create hosts FQDN.
`
